### PR TITLE
Update kubernetes dependencies to 1.14

### LINKED ISSUE #63: make generate-types creates uncompilable code
If I run `make generate-types` , I can no longer build the cassandra-operator.

```
make setup
cd cassandra-operator
go build cmd/operator/main.go

make generate-types

go build cmd/operator/main.go 
# github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/client/clientset/versioned/scheme
pkg/client/clientset/versioned/scheme/register.go:39:2: undefined: "github.com/sky-uk/cassandra-operator/cassandra-operator/vendor/k8s.io/apimachinery/pkg/util/runtime".Must
```

### PR DESCRIPTION
**Pull request by kragniz**
This seems to fix #63.

### CODE REVIEW

**Comment by alangibson01** [comment]
@kragniz Changes look fine to me. I've restarted the Travis build, just in case the status reporting issue was a transient problem. Hopefully it'll be fine, because other PR builds have succeeded without problems.

**Comment by alangibson01** [comment]
Seems to be happy now.

**Comment by alangibson01** [comment]
@kragniz @wallrj I've noticed your comments on issues today have all been in the future. For example, if you look at the thread above, you'll see that your message "I think github is having some issues..." is right at the end, whereas it should be above my comments. Have you seen that before?

**Comment by kragniz** [comment]
@alangibson01 I'm seeing the same, I think github was having various problems earlier when I wrote that comment (and travis didn't report the build status properly). I've not seen it before and I hope it doesn't happen again, since it's rather confusing!

**Pull request merged**
